apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-persistance-volume
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
